-- 为 users 表添加用户画像与通知偏好字段
ALTER TABLE users ADD COLUMN position VARCHAR(255) NULL COMMENT '用户职位';
ALTER TABLE users ADD COLUMN address VARCHAR(255) NULL COMMENT '所在地区';
ALTER TABLE users ADD COLUMN per_website VARCHAR(100) NULL COMMENT '个人网站';
ALTER TABLE users ADD COLUMN phone VARCHAR(50) NULL COMMENT '绑定手机号';
ALTER TABLE users ADD COLUMN is_hide TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否隐藏';
ALTER TABLE users ADD COLUMN is_notifisys TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否接收系统通知';
ALTER TABLE users ADD COLUMN is_notiftrends TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否接收项目动态';
ALTER TABLE users ADD COLUMN is_notifipost TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否接收产品推荐和活动资讯';
